name: captinai
description: Your app description
version: 1.0.0

environment:
  sdk: '^3.4.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_bloc: ^8.0.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  path: ^1.8.0
  url_launcher: ^6.3.0
  google_mobile_ads: ^5.1.0
  shared_preferences: ^2.2.3
  speech_to_text: ^6.6.2
  responsive_framework: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/image/splash_image.png

  fonts:
    - family: Noto Kufi Arabic
      fonts:
        - asset: lib/assets/fonts/NotoKufiArabic-VariableFont_wght.ttf
          weight: 700

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
