name: captinai
description: Your app description
version: 1.0.0

environment:
  sdk: '^3.4.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_bloc: ^8.0.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  path: ^1.8.0

fonts:
  - family: Noto Kufi Arabic
    fonts:
      - asset: assets/fonts/NotoKufiArabic-VariableFont_wght.ttf
        weight: 700

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
